# This config file is used by ros2_control for CR5 Dual Arm Robot
controller_manager:
  ros__parameters:
    update_rate: 60  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ocs2_arm_controller:
      type: ocs2_arm_controller/Ocs2ArmController

    # Gripper controllers (AG2F90-C-Soft by default)
    left_hand_controller:
      type: adaptive_gripper_controller/AdaptiveGripperController

# OCS2 Arm Controller Configuration
ocs2_arm_controller:
  ros__parameters:
    # Joint configuration
    update_rate: 60  # Hz
    mpc_frequency: 30.0
    info_file_name: left  # Use task.info file
    joints:
      # Left arm joints (6 DOF)
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6

    command_interfaces:
      - position
    state_interfaces:
      - position

    robot_name: cr5_dual

    future_time_offset: 1.1

    # Control parameters
    home_pos: [ 1.862664103107961, 0.8990284407145777, 1.23546624127555, 1.507392028165063, 0.2953757854150009, -2.003376344801695]
    rest_pos: [ 1.821591635054889, 0.2691931006968403, 2.005251609651286, 1.1064247702277883, 0.680543440980729, -1.7718580346524049 ]

# Left Hand Controller (AG2F90-C-Soft)
left_hand_controller:
  ros__parameters:
    joint: left_gripper_joint
    use_effort_interface: false
    # force_feedback_ratio: 0.1
    # force_threshold: 1.5
